<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class GripliCvBundleDocumentCvHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['title'])) {
            $value = $data['title'];
            $return = (string) $value;
            $this->class->reflFields['title']->setValue($document, $return);
            $hydratedData['title'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['reference'])) {
            $value = $data['reference'];
            $return = (string) $value;
            $this->class->reflFields['reference']->setValue($document, $return);
            $hydratedData['reference'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['statut'])) {
            $value = $data['statut'];
            $return = (string) $value;
            $this->class->reflFields['statut']->setValue($document, $return);
            $hydratedData['statut'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['viewcount'])) {
            $value = $data['viewcount'];
            $return = (int) $value;
            $this->class->reflFields['viewcount']->setValue($document, $return);
            $hydratedData['viewcount'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['remuneration'])) {
            $value = $data['remuneration'];
            $return = (int) $value;
            $this->class->reflFields['remuneration']->setValue($document, $return);
            $hydratedData['remuneration'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['grade'])) {
            $value = $data['grade'];
            $return = (string) $value;
            $this->class->reflFields['grade']->setValue($document, $return);
            $hydratedData['grade'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['user'])) {
            $reference = $data['user'];
            if (isset($this->class->fieldMappings['user']['simple']) && $this->class->fieldMappings['user']['simple']) {
                $className = $this->class->fieldMappings['user']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['user'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['user']->setValue($document, $return);
            $hydratedData['user'] = $return;
        }
        return $hydratedData;
    }
}